### ISSUE TITLE
这个好像是旧版的，新版的有空气，风力，时间。

### ISSUE THREAD

**Issue by csh159** [LazyIonEs/TwentyFourHour#1]

**Comment by LazyIonEs** [comment]
因为需求原因，没有加上空气，风力，逻辑和天气icon后的背景块差不多，可以去看看[这个](https://github.com/zx391324751/MoJiDemo)

**Comment by csh159** [comment]
类似于这样的 https://blog.csdn.net/yuton9/article/details/118187905
